---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-webhook-app
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: os-webhook-app
  template:
    metadata:
      labels:
        application: os-webhook-app
    spec:
      serviceAccountName: os-webhook-app
      containers:
      - name: os-webhook-app
        image: paurosello/os-webhook-app:0.0.16
        args:
          - ./os-webhook-app
          - --tlsCertFile=/certs/ca.crt
          - --tlsKeyFile=/certs/tls.key
          - -alsologtostderr
          - --log_dir=/
          - -v=2
        ports:
        - containerPort: 4430
        volumeMounts:
        - name: tls
          mountPath: "/certs"
      volumes:
      - name: tls
        secret:
          secretName: os-webhook-app
---
apiVersion: v1
kind: Service
metadata:
  name: os-webhook-app
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 4430
  selector:
    application: os-webhook-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: os-webhook-app
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: os-webhook-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: os-webhook-app
    namespace: kube-system
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: os-webhook-app-cert
  namespace: kube-system
spec:
  dnsNames:
  - os-webhook-app.kube-system.svc
  - os-webhook-app.kube-system.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: os-webhook-app
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/os-webhook-app-cert
  name: mutating-os-webhook-app
  namespace: kube-system
webhooks:
  - name: awsclusters.mutating-os-webhook-app.giantswarm.io
    failurePolicy: Ignore
    clientConfig:
      service:
        name: os-webhook-app
        namespace: kube-system
        path: /awscluster
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.giantswarm.io"]
        resources:
          - "awsclusters"
        apiVersions:
          - "v1alpha2"
        operations:
          - CREATE
          - UPDATE
